### ISSUE TITLE
How to I find out if edge exists in two Vertices

### ISSUE THREAD

**Issue by sachinsawant71** [xgraphdb/mono#2]
const Graph = require('@xgraph/core');
const g = new Graph();
 
g.setVertex('foo', 'Person', { name: 'Foo Bar', age: 23 });
g.setVertex('bar', 'Person', { name: 'Bar Bar', age: 22 });
g.setEdge('foo', 'bar', 'friendOf');

How do I find out if there is an edge between 'foo' and 'bar' without specifying the edge type?

Graph::hasEdge method needs "edgeType", I don't want to specify "edgeType"

**Comment by oakfang** [comment]
That's actually a great point! I'll be sure to add this feature soon :)

**Comment by oakfang** [comment]
Fixed in 5.2.0 👍
